hbase列族:
  ADDRESS: A
  BUSINESS_LICENSE: A
  CITY: rowkey
  EMAIL: A
  INDUSTRY: A
  LEGAL_PERSON: A
  NAME: A
  PROVINCE: rowkey
  REGISTER_CAPITAL: A
  REGISTER_TIME: A
  REG_CAPITAL: rowkey
  REG_TIME: A
  STATUS: A
  TEL: A
  URBAN_AREA: A
index_table:
  ADDRESS: 'False'
  BUSINESS_LICENSE: 'False'
  CITY: 'False'
  EMAIL: 'False'
  INDUSTRY: 'True'
  LEGAL_PERSON: 'False'
  NAME: 'True'
  PROVINCE: 'False'
  REGISTER_CAPITAL: 'False'
  REGISTER_TIME: 'False'
  REG_CAPITAL: 'False'
  REG_TIME: 'True'
  STATUS: 'False'
  TEL: 'True'
  URBAN_AREA: 'False'
default:
  ADDRESS: 未知
  BUSINESS_LICENSE: 未知
  CITY: 其他城市
  EMAIL: 未知
  INDUSTRY: 未知
  LEGAL_PERSON: 未知
  NAME: 未知
  PROVINCE: 中国
  REGISTER_CAPITAL: 未知
  REGISTER_TIME: 未知
  REG_CAPITAL: '0'
  REG_TIME: '0'
  STATUS: 未知
  TEL: 未知
  URBAN_AREA: 其他区
