fieldname:
  ADDRESS: address
  BUSINESS_LICENSE: .nan
  CITY: category1
  EMAIL: .nan
  INDUSTRY: belong
  LEGAL_PERSON: .nan
  NAME: name
  PROVINCE: .nan
  REGISTER_CAPITAL: .nan
  REGISTER_TIME: .nan
  REG_CAPITAL: .nan
  REG_TIME: .nan
  STATUS: .nan
  TEL: phone
  URBAN_AREA: .nan
regular:
  ADDRESS: .nan
  BUSINESS_LICENSE: .nan
  CITY: .nan
  EMAIL: .nan
  INDUSTRY: .nan
  LEGAL_PERSON: .nan
  NAME: .nan
  PROVINCE: .nan
  REGISTER_CAPITAL: .nan
  REGISTER_TIME: .nan
  REG_CAPITAL: .nan
  REG_TIME: .nan
  STATUS: .nan
  TEL: .nan
  URBAN_AREA: .nan
Data_cleaning_regular:
  ADDRESS: .nan
  BUSINESS_LICENSE: .nan
  CITY: .nan
  EMAIL: .nan
  INDUSTRY: .nan
  LEGAL_PERSON: .nan
  NAME: .nan
  PROVINCE: .nan
  REGISTER_CAPITAL: (\d+)[.]*.*万
  REGISTER_TIME: (\d{4}).*年
  REG_CAPITAL: .nan
  REG_TIME: .nan
  STATUS: .nan
  TEL: (0\d{2,3}[-－—]*\s*\d{7,8})|(1[358479]\d{9})
  URBAN_AREA: .nan

