广东:
  深圳: true
  广州: true
  东莞: true
  佛山: true
  中山: true
  汕头: true
  江门: true
  惠州: true
  珠海: true
  湛江: true
  肇庆: true
  茂名: true
  潮州: true
  揭阳: true
  梅州: true
  清远: true
  韶关: true
  云浮: true
  阳江: true
  河源: true
  汕尾: true
直辖市:
  上海: true
  香港: true
  澳门: true
  重庆: true
  北京: true
  天津: true
江苏:
  苏州: true
  无锡: true
  南京: true
  常州: true
  南通: true
  扬州: true
  徐州: true
  盐城: true
  镇江: true
  泰州: true
  淮安: true
  宿迁: true
  连云港: true
浙江:
  杭州: true
  温州: true
  宁波: true
  金华: true
  台州: true
  嘉兴: true
  绍兴: true
  湖州: true
  丽水: true
  衢州: true
  舟山: true
山东:
  烟台: true
  潍坊: true
  青岛: true
  济南: true
  临沂: true
  淄博: true
  济宁: true
  聊城: true
  德州: true
  泰安: true
  威海: true
  菏泽: true
  东营: true
  滨州: true
  枣庄: true
  日照: true
  莱芜: true
河北:
  石家庄: true
  保定: true
  沧州: true
  唐山: true
  邯郸: true
  邢台: true
  廊坊: true
  衡水: true
  秦皇岛: true
  张家口: true
  承德: true
福建:
  福州: true
  泉州: true
  厦门: true
  漳州: true
  莆田: true
  南平: true
  三明: true
  宁德: true
  龙岩: true
辽宁:
  沈阳: true
  大连: true
  鞍山: true
  丹东: true
  锦州: true
  营口: true
  铁岭: true
  葫芦岛: true
  本溪: true
  朝阳: true
  抚顺: true
  盘锦: true
  辽阳: true
  阜新: true
四川:
  成都: true
  绵阳: true
  德阳: true
  宜宾: true
  南充: true
  自贡: true
  内江: true
  泸州: true
  乐山: true
  达州: true
  广元: true
  攀枝花: true
  眉山: true
  凉山: true
  广安: true
  资阳: true
  遂宁: true
  雅安: true
  巴中: true
  阿坝: true
  甘孜: true
  阿坝藏族羌族自治州: true
  甘孜藏族自治州: true
  凉山彝族自治州: true
河南:
  郑州: true
  洛阳: true
  南阳: true
  安阳: true
  新乡: true
  驻马店: true
  焦作: true
  周口: true
  许昌: true
  商丘: true
  平顶山: true
  濮阳: true
  信阳: true
  开封: true
  漯河: true
  鹤壁: true
  三门峡: true
  省直辖县级行政区划: true
安徽:
  合肥: true
  安庆: true
  阜阳: true
  蚌埠: true
  芜湖: true
  滁州: true
  马鞍山: true
  宣城: true
  宿州: true
  六安: true
  淮南: true
  巢湖: true
  淮北: true
  黄山: true
  亳州: true
  铜陵: true
  池州: true
湖北:
  武汉: true
  宜昌: true
  襄阳: true
  十堰: true
  荆州: true
  孝感: true
  黄石: true
  荆门: true
  恩施: true
  咸宁: true
  仙桃: true
  鄂州: true
  随州: true
  天门: true
  潜江: true
  淮南: true
  蚌埠: true
  黄冈: true
  恩施土家族苗族自治州: true
  省直辖县级行政区划: true
湖南:
  长沙: true
  株洲: true
  岳阳: true
  常德: true
  衡阳: true
  邵阳: true
  湘潭: true
  郴州: true
  怀化: true
  益阳: true
  永州: true
  娄底: true
  湘西: true
  张家界: true
  湘西土家族苗族自治州: true
黑龙江:
  哈尔滨: true
  齐齐哈尔: true
  牡丹江: true
  大庆: true
  佳木斯: true
  鸡西: true
  黑河: true
  绥化: true
  伊春: true
  鹤岗: true
  双鸭山: true
  七台河: true
  大兴安岭: true
  大兴安岭地区: true
山西:
  太原: true
  临汾: true
  长治: true
  运城: true
  晋中: true
  吕梁: true
  晋城: true
  忻州: true
  大同: true
  阳泉: true
  朔州: true
吉林:
  吉林: true
  长春: true
  延边: true
  四平: true
  通化: true
  白城: true
  松原: true
  白山: true
  辽源: true
  延边朝鲜族自治州: true
广西:
  南宁: true
  桂林: true
  柳州: true
  玉林: true
  梧州: true
  北海: true
  百色: true
  河池: true
  钦州: true
  贵港: true
  防城港: true
  贺州: true
  崇左: true
  来宾: true
江西:
  南昌: true
  赣州: true
  上饶: true
  九江: true
  宜春: true
  吉安: true
  抚州: true
  萍乡: true
  景德镇: true
  新余: true
  鹰潭: true
陕西:
  西安: true
  宝鸡: true
  咸阳: true
  渭南: true
  汉中: true
  榆林: true
  延安: true
  安康: true
  商洛: true
  铜川: true
云南:
  昆明: true
  曲靖: true
  红河: true
  玉溪: true
  楚雄: true
  大理: true
  昭通: true
  保山: true
  普洱: true
  文山: true
  临沧: true
  丽江: true
  西双版纳: true
  德宏: true
  怒江: true
  迪庆: true
  楚雄彝族自治州: true
  红河哈尼族彝族自治州: true
  文山壮族苗族自治州: true
  西双版纳傣族自治州: true
  大理白族自治州: true
  德宏傣族景颇族自治州: true
  怒江傈僳族自治州: true
  迪庆藏族自治州: true
新疆:
  乌鲁木齐: true
  巴音郭楞: true
  昌吉: true
  伊犁: true
  阿克苏: true
  喀什: true
  克拉玛依: true
  塔城: true
  阿勒泰: true
  和田: true
  哈密: true
  吐鲁番: true
  博尔塔拉: true
  石河子: true
  吐鲁番地区: true
  哈密地区: true
  昌吉回族自治州: true
  博尔塔拉蒙古自治州: true
  巴音郭楞蒙古自治州: true
  阿克苏地区: true
  克孜勒苏柯尔克孜自治州: true
  喀什地区: true
  和田地区: true
  伊犁哈萨克自治州: true
  塔城地区: true
  阿勒泰地区: true
  自治区直辖县级行政区划: true
甘肃:
  兰州: true
  庆阳: true
  天水: true
  酒泉: true
  张掖: true
  武威: true
  定西: true
  陇南: true
  平凉: true
  白银: true
  临夏: true
  金昌: true
  甘南: true
  嘉峪关: true
  临夏回族自治州: true
  甘南藏族自治州: true
贵州:
  贵阳: true
  遵义: true
  黔东南: true
  六盘水: true
  黔南: true
  毕节: true
  安顺: true
  铜仁: true
  黔西南: true
  黔南布依族苗族自治州: true
  黔西南布依族苗族自治州: true
  黔东南州: true
内蒙古:
  呼和浩特: true
  包头: true
  赤峰: true
  呼伦贝尔: true
  通辽: true
  鄂尔多斯: true
  兴安盟: true
  乌兰察布: true
  巴彦淖尔: true
  乌海: true
  锡林郭勒: true
  锡林郭勒盟: true
  阿拉善盟: true
宁夏:
  银川: true
  石嘴山: true
  固原: true
  吴忠: true
  中卫: true
青海:
  西宁: true
  海西: true
  海东: true
  黄南: true
  海北: true
  青海海南: true
  玉树: true
  海北藏族自治州: true
  黄南藏族自治州: true
  海南藏族自治州: true
  果洛藏族自治州: true
  玉树藏族自治州: true
  海西蒙古族藏族自治州: true
西藏:
  拉萨: true
  日喀则: true
  林芝: true
  阿里: true
  昌都地区: true
  山南地区: true
  那曲地区: true
  阿里地区: true
  林芝地区: true
海南:
  海口: true
  三亚: true
  琼中: true
  省直辖县级行政区划: true